example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist, show_wishlist_ajax, create_wishlist_ajax
from wishlist.views import show_xml, show_xml_by_id
from wishlist.views import show_json, show_json_by_id
from wishlist.views import register, login_user, logout_user

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('ajax/', show_wishlist_ajax, name='show_wishlist_ajax'),
    path('ajax/submit/', create_wishlist_ajax, name='create_wishlist_ajax'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.
class ItemWishlist(models.Model):
    item_name = models.CharField(max_length=50)
    item_price = models.IntegerField()
    description = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
import datetime
from django.urls import reverse
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from wishlist.models import ItemWishlist

# Create your views here.
@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_wishlist_item = ItemWishlist.objects.all()
    context = {
        'list_item': data_wishlist_item,
        'name': 'Swas',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist.html", context)

@login_required(login_url='/wishlist/login/')
def show_wishlist_ajax(request):
    return render(request, "wishlist_ajax.html")

@login_required(login_url='/wishlist/login/')
@csrf_exempt
def create_wishlist_ajax(request):
    if request.method == "POST":
        item_name = request.POST.get("item_name")
        item_price = request.POST.get("item_price")
        description = request.POST.get("description")
        ItemWishlist.objects.create(item_name=item_name, item_price=item_price, description=description)
        return HttpResponse()
       
    else:
        return redirect("wishlist:show_wishlist_ajax'")

def show_xml(request):
    data = ItemWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = ItemWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = ItemWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")
    
def show_json_by_id(request, id):
    data = ItemWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Account successfully created!")
            print("masuk pak eko")
            return redirect("wishlist:login")
    
    context = {"form":form}
    return render(request, "register.html", context)

def login_user(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, "Wrong Username or Password!")
    
    context = {}
    return render(request, "login.html", context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <style>
    
  </style>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/create_wishlist_ajax.html
{% extends 'base.html' %}

{% block meta %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    
    
</script>
<title>Create</title>
{% endblock meta %}


{% block content %}
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Swastika Nata</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        
            <form class="d-flex ms-auto" role="search">
                <a class="btn btn-outline-danger" href="{% url 'wishlist:logout' %}" role="button">Logout</a>
            </form>
        </div>
    </div>
</nav>

<div class = "create">

    <h1>Create Wishlist</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Item name: </td>
                <td><input type="text" name="item_name" placeholder="Item Name" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Item price: </td>
                <td><input type="text" name="item_price" placeholder="Item Price" class="form-control"></td>
            </tr>
            <tr>
                <td>Description: </td>
                <td><input type="text" name="description" placeholder="Description" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn btn-outline-dark" type="submit" value="Submit"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     

</div>
{% endblock content %}

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn btn-outline-dark" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Don't have an account? <a href="{% url 'wishlist:register' %}">Create Account</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Account Registration</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Registration Form</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Register" class="btn btn-outline-dark"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Swastika Nata</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        
            <form class="d-flex ms-auto" role="search">
                <a class="btn btn-outline-danger" href="{% url 'wishlist:logout' %}" role="button">Logout</a>
            </form>
        </div>
    </div>
</nav>

<div class="m-3">
    <h2>Name: {{name}}</h2>

    <table class="katalog mt-3">
        <tr>
        <th>Item Name</th>
        <th>Item Price</th>
        <th>Description</th>
        </tr>
    
        {% for item in list_item %}
            <tr>
                <td>{{item.item_name}}</td>
                <td>{{item.item_price}}</td>
                <td>{{item.description}}</td>
            </tr>
        {% endfor %}
    </table>
    <p class="mt-3">Last Login: {{ last_login }}</p>
</div>


{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}

{% block meta %}
<title>Wishlist</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>

    function updateTable() {
        $.get("http://127.0.0.1:8000/wishlist/json/", function(data) {
            
            for (i = 0; i < data.length; i++) {
                var nama = document.createElement("td");
                nama.append(data[i].fields.item_name);
                var harga = document.createElement("td");
                harga.append(data[i].fields.item_price);
                var desc = document.createElement("td");
                desc.append(data[i].fields.description);
                var row = document.createElement("tr");
                row.append(nama);
                row.append(harga);
                row.append(desc)
                
                $(".katalog").append(row);
            }
        });
    }
    $(document).ready(function(){
        updateTable();
        $("#add_wishlist").click(function(){
            var item_name = $("#item_name").val();
            var item_price = parseInt($("#item_price").val());
            var description = $("#description").val();

            if (item_name != null && item_price >= 0 && description != null) {
                
            
            $.post("http://127.0.0.1:8000/wishlist/ajax/submit/",
            {
                item_name,
                item_price,
                description,
            },
            function(data, status){
                console.log("add wishlist success");

                var tr = document.createElement("tr");
                var tdNama = document.createElement("td");
                tdNama.append(item_name);
                var tdHarga = document.createElement("td");
                tdHarga.append(item_price);
                var tdDeskripsi = document.createElement("td");
                tdDeskripsi.append(description);
                
                tr.append(tdNama);
                tr.append(tdHarga);
                tr.append(tdDeskripsi);
                
                $(".katalog").append(tr);

                
            });
            }
        });
    });
    
</script>
{% endblock meta %}


{% block content %}
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Swastika Nata</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        
            <form class="d-flex ms-auto" role="search">
                <a class="btn btn-outline-danger" href="{% url 'wishlist:logout' %}" role="button">Logout</a>
            </form>
        </div>
    </div>
</nav>

<div class="m-3">

    <div class = "create">

        <p>Create Wishlist</p>
    
        <form method="POST" action="">
            {% csrf_token %}
            <table>
                <tr>
                    <td>Item name: </td>
                    <td><input type="text" id="item_name" name="item_name" placeholder="Item Name" class="form-control" required></td>
                </tr>
                        
                <tr>
                    <td>Item price: </td>
                    <td><input type="number" id="item_price" name="item_price" placeholder="Item Price" class="form-control" required></td>
                </tr>
                <tr>
                    <td>Description: </td>
                    <td><input type="text" id="description" name="description" placeholder="Description" class="form-control" required></td>
                </tr>
    
                <tr>
                    <td></td>
                </tr>
            </table>
            <button id="add_wishlist" class="btn border rounded" type="button">Tambah</button>
        </form>
        
    
        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}     
    
    </div>


    <table class="katalog mt-3" id="table">
        <tr>
        <th>Item Name</th>
        <th>Item Price</th>
        <th>Description</th>
        </tr>
    </table>
    <p class="mt-3">Last Login: {{ last_login }}</p>
</div>
{% endblock content %}